
mpesa.consumer-key=I4WWeZfhceoSA4nSAH6EiVmVzTF8cxQx0WGjffwzJN7TSR6E
mpesa.consumer-secret=9Ucr4Hw4s6Ten8ESElBcn0pQxLGbMCIA9GlP5h6noI0uPo6uZVsGGFNsGfH4tOHF
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.security-credential=DE2QlGX+4wFOgM/s8zf4nXPMAmKnc8ad4+SA/NGhTacuispUnD0bxsOep1ljs3zw3D3qviH5TweH1NarHEQEImhG4aGF3Al9F+Uaw1iuNsaruk2UVAAOA6E7iJSIqTmaBFCunrBUG2G62xf6ek+ixH55wVN+U9fwbpwnR7zD/AnGmylrWeGkJ/8t4Z7lZMlFrNDIvhNuZ6WOHq3dC7UetpPpXA9qgS/Y5wIjKTp68VliN8cxYXRJyXUXfcamhBHF2nFyFORQ0zxvIuB4uspn9VA9LSdJwxhzewnNy5xm8XXoyC7MGsb5PifgCt3gFrv1mO4sSPcKPlVwKNsd1hgs6w==
mpesa.account-ref="TRIBE_SYSTEMS"

mpesa.shortcode=174379
mpesa.org-shortcode=600996
mpesa.till-number=174379
mpesa.callback-url=https://payment.tribessystems.co.ke/api/v1/payment/callback
mpesa.confirm-result-url=https://payment.tribessystems.co.ke/api/v1/payment/confirm/result
mpesa.confirm-timeout-url=https://payment.tribessystems.co.ke/api/v1/payment/confirm/timeout

#C2B
mpesa.c2b-validation-callback=https://payment.tribessystems.co.ke/api/v1/payment/c2b/validation
mpesa.c2b-confirmation-callback=https://payment.tribessystems.co.ke/api/v1/payment/c2b/confirmation

#B2C
mpesa.b2c-result-callback=https://payment.tribessystems.co.ke/api/v1/payment/B2C/result
mpesa.b2c-timeout-callback=https://payment.tribessystems.co.ke/api/v1/payment/B2C/timeout

mpesa.auth-url=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
mpesa.initiate-stk-push-url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
mpesa.query-txn-status=https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query

#C2B
mpesa.register-c-to-b-callback-url=https://sandbox.safaricom.co.ke/mpesa/c2b/v2/registerurl
mpesa.simulate-c-to-b-transaction=https://sandbox.safaricom.co.ke/mpesa/c2b/v2/simulate

#B2C
mpesa.b-to-c-url=https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest
mpesa.b-to-c-api-username=testapi

payment.secret-key=secret-key-for-password-hashing
payment.jwt-issuer-name=tribe-systems-security

springdoc.swagger-ui.path=/swagger-ui
logging.file.path=/logs/tribe_payment
